variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_IMAGE: $DOCKER_HUB_USER/$CI_PROJECT_NAME
  PLATFORM: linux/amd64,linux/arm64,linux/arm/v7

before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use

build-master:
  image: $DOCKER_HUB_USER/buildx
  stage: build
  services:
    - docker:dind
  script:
    - docker buildx build --push -t "$CI_IMAGE"
      --platform "$PLATFORM" --cache-from "$CI_IMAGE"
      --build-arg BUILDKIT_INLINE_CACHE=1 .
  only:
    - master
